name: Deploy Cloudflare Worker

on:
  push:
    paths:
      - .github/workflows/deploy.yml
      - cloudflare-worker/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    name: Deploy
    environment: 'main'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        
      - name: Navigate to Cloudflare Worker directory
        run: cd cloudflare-worker

      - name: Deploy Cloudflare Worker
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
